INSERT OR IGNORE INTO sys_menu (menu_id,menu_name,parent_id,order_num,path,component,menu_type,visible,status,perms,icon) VALUES (5000,'项目管理',0,6,'pms','','M','0','0','','project');
--;;
INSERT OR IGNORE INTO sys_role_menu (role_id,menu_id) VALUES (1,5000);
--;;
INSERT OR IGNORE INTO sys_menu (menu_id,menu_name,parent_id,order_num,path,component,menu_type,visible,status,perms,icon) VALUES (5001,'项目台账',5000,1,'project','pms/project/index','C','0','0','pms:project:list','table');
--;;
INSERT OR IGNORE INTO sys_role_menu (role_id,menu_id) VALUES (1,5001);
--;;
INSERT OR IGNORE INTO sys_menu (menu_id,menu_name,parent_id,order_num,path,component,menu_type,visible,status,perms,icon) VALUES (5002,'项目驾驶舱',5000,2,'dashboard','pms/dashboard/index','C','0','0','pms:dashboard:query','dashboard');
--;;
INSERT OR IGNORE INTO sys_role_menu (role_id,menu_id) VALUES (1,5002);
--;;
INSERT OR IGNORE INTO sys_menu (menu_id,menu_name,parent_id,order_num,path,component,menu_type,visible,status,perms,icon) VALUES (5010,'项目查询',5001,1,'','','F','0','0','pms:project:query','#');
--;;
INSERT OR IGNORE INTO sys_role_menu (role_id,menu_id) VALUES (1,5010);
--;;
INSERT OR IGNORE INTO sys_menu (menu_id,menu_name,parent_id,order_num,path,component,menu_type,visible,status,perms,icon) VALUES (5011,'项目新增',5001,2,'','','F','0','0','pms:project:add','#');
--;;
INSERT OR IGNORE INTO sys_role_menu (role_id,menu_id) VALUES (1,5011);
--;;
INSERT OR IGNORE INTO sys_menu (menu_id,menu_name,parent_id,order_num,path,component,menu_type,visible,status,perms,icon) VALUES (5012,'项目编辑',5001,3,'','','F','0','0','pms:project:edit','#');
--;;
INSERT OR IGNORE INTO sys_role_menu (role_id,menu_id) VALUES (1,5012);
--;;
INSERT OR IGNORE INTO sys_menu (menu_id,menu_name,parent_id,order_num,path,component,menu_type,visible,status,perms,icon) VALUES (5013,'状态推进',5001,4,'','','F','0','0','pms:project:transition','#');
--;;
INSERT OR IGNORE INTO sys_role_menu (role_id,menu_id) VALUES (1,5013);
--;;
INSERT OR IGNORE INTO sys_menu (menu_id,menu_name,parent_id,order_num,path,component,menu_type,visible,status,perms,icon) VALUES (5014,'节点新增',5001,5,'','','F','0','0','pms:node:add','#');
--;;
INSERT OR IGNORE INTO sys_role_menu (role_id,menu_id) VALUES (1,5014);
--;;
INSERT OR IGNORE INTO sys_menu (menu_id,menu_name,parent_id,order_num,path,component,menu_type,visible,status,perms,icon) VALUES (5015,'成员维护',5001,6,'','','F','0','0','pms:member:edit','#');
--;;
INSERT OR IGNORE INTO sys_role_menu (role_id,menu_id) VALUES (1,5015);
--;;
