INSERT IGNORE INTO sys_menu(menu_id,menu_name,parent_id,order_num,path,component,menu_type,visible,status,perms,icon) VALUES (5030,'计划审批',5001,10,'','','F','0','0','pms:plan:approve','#');
--;;
INSERT IGNORE INTO sys_role_menu(role_id,menu_id) VALUES (1,5030);
--;;
INSERT IGNORE INTO sys_menu(menu_id,menu_name,parent_id,order_num,path,component,menu_type,visible,status,perms,icon) VALUES (5031,'质量与治理审批',5001,11,'','','F','0','0','pms:quality:approve','#');
--;;
INSERT IGNORE INTO sys_role_menu(role_id,menu_id) VALUES (1,5031);
--;;
INSERT IGNORE INTO sys_menu(menu_id,menu_name,parent_id,order_num,path,component,menu_type,visible,status,perms,icon) VALUES (5032,'工时审批',5001,12,'','','F','0','0','pms:time:approve','#');
--;;
INSERT IGNORE INTO sys_role_menu(role_id,menu_id) VALUES (1,5032);
--;;
INSERT IGNORE INTO sys_menu(menu_id,menu_name,parent_id,order_num,path,component,menu_type,visible,status,perms,icon) VALUES (5033,'财务查看',5001,13,'','','F','0','0','pms:finance:query','#');
--;;
INSERT IGNORE INTO sys_role_menu(role_id,menu_id) VALUES (1,5033);
--;;
INSERT IGNORE INTO sys_menu(menu_id,menu_name,parent_id,order_num,path,component,menu_type,visible,status,perms,icon) VALUES (5034,'财务维护',5001,14,'','','F','0','0','pms:finance:edit','#');
--;;
INSERT IGNORE INTO sys_role_menu(role_id,menu_id) VALUES (1,5034);
--;;
INSERT IGNORE INTO sys_menu(menu_id,menu_name,parent_id,order_num,path,component,menu_type,visible,status,perms,icon) VALUES (5035,'财务审批',5001,15,'','','F','0','0','pms:finance:approve','#');
--;;
INSERT IGNORE INTO sys_role_menu(role_id,menu_id) VALUES (1,5035);
--;;
INSERT IGNORE INTO sys_menu(menu_id,menu_name,parent_id,order_num,path,component,menu_type,visible,status,perms,icon) VALUES (5036,'项目关闭审批',5001,16,'','','F','0','0','pms:project:close','#');
--;;
INSERT IGNORE INTO sys_role_menu(role_id,menu_id) VALUES (1,5036);
--;;
INSERT IGNORE INTO sys_menu(menu_id,menu_name,parent_id,order_num,path,component,menu_type,visible,status,perms,icon) VALUES (5037,'项目受控重开',5001,17,'','','F','0','0','pms:project:reopen','#');
--;;
INSERT IGNORE INTO sys_role_menu(role_id,menu_id) VALUES (1,5037);
--;;
INSERT IGNORE INTO sys_menu(menu_id,menu_name,parent_id,order_num,path,component,menu_type,visible,status,perms,icon) VALUES (5038,'集成查看',5001,18,'','','F','0','0','pms:integration:query','#');
--;;
INSERT IGNORE INTO sys_role_menu(role_id,menu_id) VALUES (1,5038);
--;;
INSERT IGNORE INTO sys_menu(menu_id,menu_name,parent_id,order_num,path,component,menu_type,visible,status,perms,icon) VALUES (5039,'集成配置',5001,19,'','','F','0','0','pms:integration:edit','#');
--;;
INSERT IGNORE INTO sys_role_menu(role_id,menu_id) VALUES (1,5039);
--;;
INSERT IGNORE INTO sys_menu(menu_id,menu_name,parent_id,order_num,path,component,menu_type,visible,status,perms,icon) VALUES (5040,'集成收件处理',5001,20,'','','F','0','0','pms:integration:receive','#');
--;;
INSERT IGNORE INTO sys_role_menu(role_id,menu_id) VALUES (1,5040);
--;;
INSERT IGNORE INTO sys_menu(menu_id,menu_name,parent_id,order_num,path,component,menu_type,visible,status,perms,icon) VALUES (5041,'集成发件处理',5001,21,'','','F','0','0','pms:integration:deliver','#');
--;;
INSERT IGNORE INTO sys_role_menu(role_id,menu_id) VALUES (1,5041);
--;;
